# Generated by Django 5.0.6 on 2024-07-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='link_localizacao',
            field=models.URLField(blank=True, default='', max_length=3000, null=True, verbose_name='Link Localização'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link_reunião',
            field=models.CharField(blank=True, default='', max_length=3000, null=True, verbose_name='Link Reunião'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Localização'),
        ),
    ]
