# Generated by Django 5.0.6 on 2024-07-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_link_localizacao_and_more'),
        ('perfil', '0013_videochamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convite_evento_destinatario', to='perfil.perfil', verbose_name='Destinatário')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convite_evento_remetentes', to='perfil.perfil', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Convite Evento',
                'verbose_name_plural': 'Convite Evento',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Evento', 'Evento'), ('Chamada Video', 'Chamada Video')], default='Evento', max_length=255, verbose_name='Tipo')),
                ('confirmacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação')),
                ('convite_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.conviteevento', verbose_name='Convite Evento')),
                ('video_chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.videochamada', verbose_name='Vídeo Chamada')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='ParticipantesEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_evento_remetentes', to='perfil.perfil', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Participante Evento',
                'verbose_name_plural': 'Participantes Evento',
            },
        ),
    ]
