# Generated by Django 5.0.6 on 2024-07-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_visibilidade'),
        ('perfil', '0016_alter_perfil_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='convite_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.conviteevento', verbose_name='Convite Evento'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='video_chamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.videochamada', verbose_name='Vídeo Chamada'),
        ),
    ]
