# Generated by Django 5.0.6 on 2024-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_conviteevento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conviteevento',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Descrição'),
        ),
    ]
