# Generated by Django 5.0.6 on 2024-07-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_conviteevento_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='link_reunião',
            new_name='link_reuniao',
        ),
    ]
