# Generated by Django 5.0.6 on 2024-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_rename_link_reunião_evento_link_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='qtd_participantes',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
