# Generated by Django 5.0.6 on 2024-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_qtd_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantesevento',
            name='img_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='participantesevento',
            name='link_confirmacao',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link Confirmação'),
        ),
    ]
