# Generated by Django 5.0.6 on 2024-08-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_participantesevento_img_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantesevento',
            name='comparecer_evento',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação'),
        ),
    ]
