# Generated by Django 5.0.6 on 2024-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_participantesevento_comparecer_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantesevento',
            name='comparecer_evento',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Apareceu no evento?'),
        ),
    ]
