# Generated by Django 5.0.6 on 2024-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_participantesevento_comparecer_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='eventos_videos/%Y/%m/%d', verbose_name='Vídeo'),
        ),
    ]
