# Generated by Django 5.0.6 on 2024-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_evento_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='video',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Link vídeo'),
        ),
    ]
