# Generated by Django 5.0.6 on 2024-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_evento_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantesevento',
            name='codigo',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Código'),
        ),
    ]
