# Generated by Django 5.0.6 on 2024-08-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_participantesevento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantesevento',
            name='bilhete',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Bilhete'),
        ),
    ]
