# Generated by Django 5.0.6 on 2024-08-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_participantesevento_bilhete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantesevento',
            name='bilhete',
            field=models.FileField(blank=True, default=None, null=True, upload_to='bilhetes/%Y/%m/%d', verbose_name='Bilhete'),
        ),
    ]
