# Generated by Django 5.0.6 on 2024-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_alter_participantesevento_bilhete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantesevento',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Código'),
        ),
    ]
