# Generated by Django 5.0.6 on 2024-08-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_alter_participantesevento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='eventos_videos/%Y/%m/%d', verbose_name='Link vídeo'),
        ),
    ]
