# Generated by Django 5.0.6 on 2024-08-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_evento_video2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='eventos_videos/%Y/%m/%d', verbose_name='Arquivo de vídeo'),
        ),
    ]
