# Generated by Django 5.0.6 on 2024-08-08 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_alter_evento_video2'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='contato1',
            field=models.CharField(blank=True, default='', help_text='Ex: +44 7911 123456', max_length=1000, null=True, verbose_name='Contato 1*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='contato2',
            field=models.CharField(blank=True, default='', help_text='Ex: +44 7911 123456', max_length=1000, null=True, verbose_name='Contato 2*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data Término*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='divisao_genero',
            field=models.BooleanField(default=False, help_text='\n                                        Se marcar essa opção, os ingressos serão divididos em 50%. \n                                        Exemplo: se tem 20 ingressos, 10 serão de homens e 10 de mulheres.\n                                        ', verbose_name='Divisão de Gênero'),
        ),
        migrations.AddField(
            model_name='evento',
            name='duracao_numero',
            field=models.IntegerField(default=0, verbose_name='Duração (Número)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='duracao_tipo',
            field=models.CharField(choices=[('minutos', 'minutos'), ('horas', 'horas'), ('dias', 'dias')], default='minutos', max_length=255, verbose_name='Tipo da Duração'),
        ),
        migrations.AddField(
            model_name='evento',
            name='faixa_etaria',
            field=models.CharField(blank=True, default='', help_text='Ex: 18 - 50 anos', max_length=100, null=True, verbose_name='Faixa Etária*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_localizacao_inicio',
            field=models.URLField(blank=True, default='', help_text='LINK GOOGLE MAPS', max_length=3000, null=True, verbose_name='Link Localização Início*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='localizacao_inicio',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Localização Início*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='maximo_participantes',
            field=models.IntegerField(default=1, verbose_name='Máximo de Participantes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='mensagem_administrador',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Nota do administrador*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='mensagem_motivo',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Campo "por que ir para o evento?" *'),
        ),
        migrations.AddField(
            model_name='evento',
            name='permanencia_noturna',
            field=models.BooleanField(default=False, verbose_name='Permanência noturna?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_crianca',
            field=models.FloatField(default=0, help_text='Caso não queira essa opção, deixe como 0', verbose_name='Valor Criança*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_homem',
            field=models.FloatField(default=0, help_text='Caso não queira essa opção, deixe como 0', verbose_name='Valor Homem*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_mulher',
            field=models.FloatField(default=0, help_text='Caso não queira essa opção, deixe como 0', verbose_name='Valor Mulher*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link_localizacao',
            field=models.URLField(blank=True, default='', help_text='LINK GOOGLE MAPS', max_length=3000, null=True, verbose_name='Link Localização*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link_reuniao',
            field=models.CharField(blank=True, default='', help_text='Apenas se o evento for online', max_length=3000, null=True, verbose_name='Link Reunião*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='localizacao',
            field=models.CharField(blank=True, default='', help_text='Localização do evento em si', max_length=1000, null=True, verbose_name='Localização*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.FloatField(default=0, help_text='\n                              Se o evento for gratuito, desconsidere esse campo e os 3 de baixo.\n                              Se o evento for pago, preencha esse campo e fique atento aos detalhes.\n                              Apenas se o preço for igual para todos os gêneros.\n                              Se você for fazer divisão de preço de acordo com o gênero, \n                              deixe esse campo como 0 e preencha os 3 campos abaixo.\n                              ', verbose_name='Valor Geral*'),
        ),
    ]
