# Generated by Django 5.0.6 on 2024-08-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_evento_contato1_evento_contato2_evento_data_termino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=3000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Atividade Turistica',
                'verbose_name_plural': 'Atividades Turisticas',
            },
        ),
        migrations.CreateModel(
            name='DetalheDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=5000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Detalhe do Dia',
                'verbose_name_plural': 'Detalhes dos Dias',
            },
        ),
        migrations.CreateModel(
            name='GaleriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=1000, verbose_name='Nome')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='galeria_eventos/%Y/%m/%d', verbose_name='Foto 1')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='galeria_eventos/%Y/%m/%d', verbose_name='Foto 2')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='galeria_eventos/%Y/%m/%d', verbose_name='Foto 3')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='galeria_eventos/%Y/%m/%d', verbose_name='Foto 4')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='galeria_eventos/%Y/%m/%d', verbose_name='Foto 5')),
            ],
            options={
                'verbose_name': 'Galeria do Evento',
                'verbose_name_plural': 'Galerias do Evento',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=3000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=3000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=2000, verbose_name='Pergunta')),
                ('texto', models.TextField(default='', max_length=5000, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='info_guia_turistico',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Informação Guia Turístico" *'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_fotos/%Y/%m/%d', verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='localizacao_inicio',
            field=models.CharField(blank=True, default='', help_text='Ponto de partida', max_length=1000, null=True, verbose_name='Localização Início*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='mensagem_administrador',
            field=models.TextField(blank=True, default='', help_text='Escreva uma mensagem/observação do administrador do evento', max_length=10000, null=True, verbose_name='Nota do administrador*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='mensagem_motivo',
            field=models.TextField(blank=True, default='', help_text='Explique o motivo do por quê as pessoas deveriam ir para o evento', max_length=10000, null=True, verbose_name='Campo "por que ir para o evento?" *'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='permanencia_noturna',
            field=models.BooleanField(default=False, help_text='As pessoas vão dormir no evento?', verbose_name='Permanência noturna'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video',
            field=models.URLField(blank=True, help_text='Link do youtube: vá em compartilhar -> incorporar -> pegue o link dentro de "src"', max_length=2000, null=True, verbose_name='Link vídeo*'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='video2',
            field=models.FileField(blank=True, help_text='Arquivo de vídeo. Evite vídeos com mais de 100mb, para evitar vídeos pesados no sistema', null=True, upload_to='eventos_videos/%Y/%m/%d', verbose_name='Arquivo de vídeo*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='detalhes_dias',
            field=models.ManyToManyField(blank=True, help_text='Explique os detalhes dos dias do evento', related_name='detalhes_dias', to='eventos.detalhedia', verbose_name='Detalhes dos dias*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='galeria',
            field=models.OneToOneField(blank=True, help_text='Primeiro, crie uma galeria de fotos para o evento e adicione aqui. Você pode escolher\n                                   até 5 fotos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.galeriaevento', verbose_name='Galeria'),
        ),
        migrations.AddField(
            model_name='evento',
            name='itens_exclusos',
            field=models.ManyToManyField(blank=True, related_name='itens_exclusos', to='eventos.item', verbose_name='Itens NÃO Inclusos*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='itens_inclusos',
            field=models.ManyToManyField(blank=True, related_name='itens_inclusos', to='eventos.item', verbose_name='Itens Inclusos*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugares_visitas',
            field=models.ManyToManyField(blank=True, help_text='Lugares que serão visitados', related_name='lugares', to='eventos.lugar', verbose_name='Lugares*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pergunta',
            field=models.ManyToManyField(blank=True, help_text='Coloque a pergunta frequente e explique com detalhes a sua resposta', related_name='perguntas', to='eventos.perguntafrequente', verbose_name='Perguntas Frequentes*'),
        ),
    ]
