# Generated by Django 5.0.6 on 2024-08-08 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_atividadeturistica_detalhedia_galeriaevento_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='itens_exclusos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='itens_inclusos',
        ),
        migrations.AddField(
            model_name='evento',
            name='itens_exclusos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_exclusos', to='eventos.item', verbose_name='Itens NÃO Inclusos*'),
        ),
        migrations.AddField(
            model_name='evento',
            name='itens_inclusos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inclusos', to='eventos.item', verbose_name='Itens Inclusos*'),
        ),
    ]
