# Generated by Django 5.0.6 on 2024-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_remove_evento_itens_exclusos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='divisao_genero',
            field=models.CharField(choices=[('nenhum', 'nenhum'), ('metade', 'metade'), ('homem', 'homem'), ('mulher', 'mulher')], default='nenhum', help_text='\n        Se marcar essa opção, os ingressos serão divididos em 50%. \n        Exemplo: se tem 20 ingressos, 10 serão de homens e 10 de mulheres.\n        ', max_length=255, verbose_name='Divisão de Gênero'),
        ),
    ]
