# Generated by Django 5.0.6 on 2024-08-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_alter_evento_divisao_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='divisao_genero',
            field=models.CharField(choices=[('nenhum', 'nenhum'), ('metade', 'metade'), ('homem', 'homem'), ('mulher', 'mulher')], default='nenhum', help_text='\n        Essa opção divide os ingressos para só mulheres, só homens ou divide na metade, em 50%.\n        Se não quiser dividir por gênero, deixe marcado como "nenhum".\n        ', max_length=255, verbose_name='Divisão de Gênero'),
        ),
    ]
