# Generated by Django 5.0.6 on 2024-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_alter_evento_divisao_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='qtd_participantes_homens',
            field=models.IntegerField(default=1, verbose_name='Quantidade Homem'),
        ),
        migrations.AddField(
            model_name='evento',
            name='qtd_participantes_mulheres',
            field=models.IntegerField(default=1, verbose_name='Quantidade Homem'),
        ),
    ]
