# Generated by Django 5.0.6 on 2024-08-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_evento_qtd_participantes_homens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='presenca_crianca',
            field=models.BooleanField(default=False, help_text='Marque se o evento pode ter criança ou não', verbose_name='O evento pode ter criança?'),
        ),
    ]
