# Generated by Django 5.0.6 on 2024-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_evento_presenca_crianca'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='idade_crianca',
            field=models.CharField(default='', help_text='Marque apenas se o evento for ter criança.', max_length=300, verbose_name='Idade Máxima da Criança*'),
        ),
    ]
