# Generated by Django 5.0.6 on 2024-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_categoria_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='idade_crianca',
            field=models.IntegerField(default=12, help_text='Marque apenas se o evento for ter criança. Ex: 12 anos', verbose_name='Idade Máxima da Criança*'),
        ),
    ]
