# Generated by Django 5.0.6 on 2024-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_alter_evento_idade_crianca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='qtd_participantes_mulheres',
            field=models.IntegerField(default=1, verbose_name='Quantidade Mulher'),
        ),
    ]
