# Generated by Django 5.0.6 on 2024-07-23 00:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros')], default='Masculino', max_length=255, verbose_name='Gênero')),
                ('aniversario', models.DateField(default=django.utils.timezone.now, verbose_name='Aniversário')),
                ('nacionalidade', models.CharField(max_length=255, verbose_name='Nacionalidade')),
                ('pais', models.CharField(choices=[('Alemanha', 'Alemanha'), ('Áustria', 'Áustria'), ('Bélgica', 'Bélgica'), ('Bulgária', 'Bulgária'), ('Chipre', 'Chipre'), ('Croácia', 'Croácia'), ('Dinamarca', 'Dinamarca'), ('Eslováquia', 'Eslováquia'), ('Eslovênia', 'Eslovênia'), ('Espanha', 'Espanha'), ('Estônia', 'Estônia'), ('Finlândia', 'Finlândia'), ('França', 'França'), ('Grécia', 'Grécia'), ('Hungria', 'Hungria'), ('Irlanda', 'Irlanda'), ('Itália', 'Itália'), ('Letônia', 'Letônia'), ('Lituânia', 'Lituânia'), ('Luxemburgo', 'Luxemburgo'), ('Malta', 'Malta'), ('Países Baixos', 'Países Baixos'), ('Polônia', 'Polônia'), ('Portugal', 'Portugal'), ('Romênia', 'Romênia'), ('Suécia', 'Suécia')], default='Alemanha', max_length=255, verbose_name='País')),
                ('celular', models.CharField(max_length=255, verbose_name='Celular')),
                ('regiao', models.CharField(max_length=255, verbose_name='Região')),
                ('interesse', models.CharField(choices=[('Relacionamento Sério', 'Relacionamento Sério'), ('Encontros', 'Encontros'), ('Namoros', 'Namoros'), ('Amizades', 'Amizades')], default='Relacionamento Sério', max_length=255, verbose_name='Interesses')),
                ('orientacao_sexual', models.CharField(choices=[('Heterossexual', 'Heterossexual'), ('Homossexual', 'Homossexual'), ('Bissexual', 'Bissexual'), ('Pansexual', 'Pansexual'), ('Assexual', 'Assexual'), ('Outros ', 'Outros')], default='Heterossexual', max_length=255, verbose_name='Orientação Sexual')),
                ('profissao', models.CharField(max_length=255, verbose_name='Profissão')),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo'), ('Separado', 'Separado'), ('Relacionamento Sério ', 'Relacionamento Sério')], default='Solteiro', max_length=255, verbose_name='Estado Civil')),
                ('signo', models.CharField(choices=[('Áries', 'Áries'), ('Touro', 'Touro'), ('Gêmeos', 'Gêmeos'), ('Câncer', 'Câncer'), ('Leão', 'Leão'), ('Virgem', 'Virgem'), ('Libra', 'Libra'), ('Escorpião', 'Escorpião'), ('Sagitário', 'Sagitário'), ('Capricórnio', 'Capricórnio'), ('Aquário', 'Aquário'), ('Peixes', 'Peixes')], default='Áries', max_length=255, verbose_name='Signo')),
                ('etnia', models.CharField(choices=[('Branco', 'Branco'), ('Negro', 'Negro'), ('Pardo', 'Pardo'), ('Indígena', 'Indígena'), ('Amarelo', 'Amarelo'), ('Outros', 'Outros')], default='Branco', max_length=255, verbose_name='Etnia')),
                ('cor_cabelo', models.CharField(choices=[('Preto', 'Preto'), ('Castanho', 'Castanho'), ('Loiro', 'Loiro'), ('Ruivo', 'Ruivo'), ('Grisalho', 'Grisalho'), ('Outros', 'Outros')], default='Preto', max_length=255, verbose_name='Cor do Cabelo')),
                ('cor_olhos', models.CharField(choices=[('Azul', 'Azul'), ('Verde', 'Verde'), ('Castanho', 'Castanho'), ('Preto', 'Preto'), ('Outro', 'Outro')], default='Azul', max_length=255, verbose_name='Cor dos Olhos')),
                ('altura', models.CharField(choices=[('Abaixo de 1,50m', 'Abaixo de 1,50m'), ('1,50m - 1,60m', '1,50m - 1,60m'), ('1,60m - 1,70m', '1,60m - 1,70m'), ('1,70m - 1,80m', '1,70m - 1,80m'), ('1,80m - 1,90m', '1,80m - 1,90m'), ('Mais de 1,90m', 'Mais de 1,90m')], default='Abaixo de 1,50m', max_length=255, verbose_name='Altura')),
                ('tipo_corpo', models.CharField(choices=[('Magro', 'Magro'), ('Normal', 'Normal'), ('Atlético', 'Atlético'), ('Gordo', 'Gordo'), ('Musculoso', 'Musculoso'), ('Outros', 'Outros')], default='Magro', max_length=255, verbose_name='Tipo do Corpo')),
                ('fuma', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=255, verbose_name='Fuma?')),
                ('bebe', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=255, verbose_name='Bebe?')),
                ('descricao', models.TextField(max_length=10000, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d', verbose_name='Foto')),
                ('usuario', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
