# Generated by Django 5.0.6 on 2024-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Slug'),
        ),
    ]
