# Generated by Django 5.0.6 on 2024-07-26 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('slug', models.SlugField(default='', max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Cupido',
                'verbose_name_plural': 'Cupidos',
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo'), ('Separado', 'Separado'), ('Relacionamento Sério', 'Relacionamento Sério')], default='Solteiro', max_length=255, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(choices=[('Alemanha', 'Alemanha'), ('Áustria', 'Áustria'), ('Bélgica', 'Bélgica'), ('Bulgária', 'Bulgária'), ('Chipre', 'Chipre'), ('Croácia', 'Croácia'), ('Dinamarca', 'Dinamarca'), ('Eslováquia', 'Eslováquia'), ('Eslovênia', 'Eslovênia'), ('Espanha', 'Espanha'), ('Estônia', 'Estônia'), ('Finlândia', 'Finlândia'), ('França', 'França'), ('Grécia', 'Grécia'), ('Hungria', 'Hungria'), ('Irlanda', 'Irlanda'), ('Itália', 'Itália'), ('Letônia', 'Letônia'), ('Lituânia', 'Lituânia'), ('Luxemburgo', 'Luxemburgo'), ('Malta', 'Malta'), ('Países Baixos', 'Países Baixos'), ('Polônia', 'Polônia'), ('Portugal', 'Portugal'), ('Romênia', 'Romênia'), ('Suécia', 'Suécia'), ('Albânia', 'Albânia'), ('Andorra', 'Andorra'), ('Armênia', 'Armênia'), ('Azerbaijão', 'Azerbaijão'), ('Bielorrússia', 'Bielorrússia'), ('Bósnia e Herzegovina', 'Bósnia e Herzegovina'), ('Cazaquistão', 'Cazaquistão'), ('Geórgia', 'Geórgia'), ('Islândia', 'Islândia'), ('Kosovo', 'Kosovo'), ('Liechtenstein', 'Liechtenstein'), ('Moldávia', 'Moldávia'), ('Mônaco', 'Mônaco'), ('Montenegro', 'Montenegro'), ('Macedônia do Norte', 'Macedônia do Norte'), ('Noruega', 'Noruega'), ('Rússia', 'Rússia'), ('San Marino', 'San Marino'), ('Sérvia', 'Sérvia'), ('Suíça', 'Suíça'), ('Turquia', 'Turquia'), ('Ucrânia', 'Ucrânia'), ('Reino Unido', 'Reino Unido'), ('Vaticano', 'Vaticano')], default='Alemanha', max_length=255, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cupido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.cupido', verbose_name='Usuário'),
        ),
    ]
