# Generated by Django 5.0.6 on 2024-07-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_cupido_alter_perfil_estado_civil_alter_perfil_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupido',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cupido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.cupido', verbose_name='Cupido'),
        ),
    ]
