# Generated by Django 5.0.6 on 2024-07-26 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_cupido_foto_alter_perfil_cupido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(default='', max_length=255, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='verificacao_email',
            field=models.BooleanField(default=False, verbose_name='Verificação'),
        ),
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recuperacao', models.BooleanField(default=False, verbose_name='Foi Recuperado?')),
                ('codigo', models.CharField(default='', max_length=255, verbose_name='Código')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recuperação de Senha',
                'verbose_name_plural': 'Recuperação de Senhas',
            },
        ),
    ]
