# Generated by Django 5.0.6 on 2024-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_perfil_codigo_perfil_verificacao_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupido',
            name='codigo',
            field=models.CharField(default='', max_length=255, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='cupido',
            name='link',
            field=models.URLField(default='', max_length=1000, verbose_name='Link'),
        ),
    ]
