# Generated by Django 5.0.6 on 2024-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_cupido_codigo_cupido_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupido',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
