# Generated by Django 5.0.6 on 2024-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_cupido_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupido',
            name='codigo',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
