# Generated by Django 5.0.6 on 2024-07-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_cupido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='verificacao_email',
            field=models.BooleanField(default=False, verbose_name='Verificação E-mail'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='album/%Y/%m/%d', verbose_name='Foto 1')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='album/%Y/%m/%d', verbose_name='Foto 2')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='album/%Y/%m/%d', verbose_name='Foto 3')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='album/%Y/%m/%d', verbose_name='Foto 4')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='album/%Y/%m/%d', verbose_name='Foto 5')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
    ]
