# Generated by Django 5.0.6 on 2024-07-29 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_alter_perfil_verificacao_email_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_reunião', models.CharField(default='', max_length=3000, verbose_name='Link Reunião')),
                ('confirmacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('descricao', models.TextField(default='', max_length=2000, verbose_name='Descrição')),
                ('cupido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.cupido', verbose_name='Cupido')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chamada_destinatario', to='perfil.perfil', verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chamada_remetente', to='perfil.perfil', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Video Chamada',
                'verbose_name_plural': 'Video Chamadas',
            },
        ),
    ]
