# Generated by Django 5.0.6 on 2024-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_alter_perfil_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='interesse',
            field=models.CharField(choices=[('Não quero relacionamentos. Só quero a parte de terapeutas', 'Não quero relacionamentos. Só quero a parte de terapeutas'), ('Não quero relacionamentos', 'Não quero relacionamentos'), ('Relacionamento Sério', 'Relacionamento Sério'), ('Encontros', 'Encontros'), ('Namoros', 'Namoros'), ('Amizades', 'Amizades')], default='Relacionamento Sério', max_length=255, verbose_name='Interesses'),
        ),
    ]
