# Generated by Django 5.0.6 on 2024-07-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_alter_perfil_interesse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videochamada',
            old_name='link_reunião',
            new_name='link_reuniao',
        ),
    ]
