# Generated by Django 5.0.6 on 2024-07-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_alter_perfil_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochamada',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Descrição'),
        ),
    ]
