# Generated by Django 5.0.6 on 2024-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_alter_videochamada_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_cancelar_assinatura',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Código C.A'),
        ),
    ]
