# Generated by Django 5.0.6 on 2024-08-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0022_alter_videochamada_link_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochamada',
            name='link_reuniao',
            field=models.CharField(default='', max_length=3000, verbose_name='Link Reunião'),
        ),
    ]
