# Generated by Django 5.0.6 on 2024-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_alter_videochamada_link_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochamada',
            name='senha_reuniao',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Senha reunião'),
        ),
    ]
