# Generated by Django 5.0.6 on 2024-08-05 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_videochamada_senha_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cupido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.cupido', verbose_name='Cupido'),
        ),
    ]
