# Generated by Django 5.0.6 on 2024-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0027_alter_perfil_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupido',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cupido',
            name='pais',
            field=models.CharField(choices=[('Alemanha', 'Alemanha'), ('Áustria', 'Áustria'), ('Bélgica', 'Bélgica'), ('Bulgária', 'Bulgária'), ('Chipre', 'Chipre'), ('Croácia', 'Croácia'), ('Dinamarca', 'Dinamarca'), ('Eslováquia', 'Eslováquia'), ('Eslovênia', 'Eslovênia'), ('Espanha', 'Espanha'), ('Estônia', 'Estônia'), ('Finlândia', 'Finlândia'), ('França', 'França'), ('Grécia', 'Grécia'), ('Hungria', 'Hungria'), ('Irlanda', 'Irlanda'), ('Itália', 'Itália'), ('Letônia', 'Letônia'), ('Lituânia', 'Lituânia'), ('Luxemburgo', 'Luxemburgo'), ('Malta', 'Malta'), ('Países Baixos', 'Países Baixos'), ('Polônia', 'Polônia'), ('Portugal', 'Portugal'), ('Romênia', 'Romênia'), ('Suécia', 'Suécia'), ('Albânia', 'Albânia'), ('Andorra', 'Andorra'), ('Armênia', 'Armênia'), ('Azerbaijão', 'Azerbaijão'), ('Bielorrússia', 'Bielorrússia'), ('Bósnia e Herzegovina', 'Bósnia e Herzegovina'), ('Cazaquistão', 'Cazaquistão'), ('Geórgia', 'Geórgia'), ('Islândia', 'Islândia'), ('Kosovo', 'Kosovo'), ('Liechtenstein', 'Liechtenstein'), ('Moldávia', 'Moldávia'), ('Mônaco', 'Mônaco'), ('Montenegro', 'Montenegro'), ('Macedônia do Norte', 'Macedônia do Norte'), ('Noruega', 'Noruega'), ('Rússia', 'Rússia'), ('San Marino', 'San Marino'), ('Sérvia', 'Sérvia'), ('Suíça', 'Suíça'), ('Turquia', 'Turquia'), ('Ucrânia', 'Ucrânia'), ('Reino Unido', 'Reino Unido'), ('Vaticano', 'Vaticano')], default='Alemanha', max_length=255, verbose_name='País'),
        ),
    ]
