# Generated by Django 5.0.6 on 2024-09-04 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_cupido_cidade_cupido_pais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradoresEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('pais', models.CharField(choices=[('Alemanha', 'Alemanha'), ('Áustria', 'Áustria'), ('Bélgica', 'Bélgica'), ('Bulgária', 'Bulgária'), ('Chipre', 'Chipre'), ('Croácia', 'Croácia'), ('Dinamarca', 'Dinamarca'), ('Eslováquia', 'Eslováquia'), ('Eslovênia', 'Eslovênia'), ('Espanha', 'Espanha'), ('Estônia', 'Estônia'), ('Finlândia', 'Finlândia'), ('França', 'França'), ('Grécia', 'Grécia'), ('Hungria', 'Hungria'), ('Irlanda', 'Irlanda'), ('Itália', 'Itália'), ('Letônia', 'Letônia'), ('Lituânia', 'Lituânia'), ('Luxemburgo', 'Luxemburgo'), ('Malta', 'Malta'), ('Países Baixos', 'Países Baixos'), ('Polônia', 'Polônia'), ('Portugal', 'Portugal'), ('Romênia', 'Romênia'), ('Suécia', 'Suécia'), ('Albânia', 'Albânia'), ('Andorra', 'Andorra'), ('Armênia', 'Armênia'), ('Azerbaijão', 'Azerbaijão'), ('Bielorrússia', 'Bielorrússia'), ('Bósnia e Herzegovina', 'Bósnia e Herzegovina'), ('Cazaquistão', 'Cazaquistão'), ('Geórgia', 'Geórgia'), ('Islândia', 'Islândia'), ('Kosovo', 'Kosovo'), ('Liechtenstein', 'Liechtenstein'), ('Moldávia', 'Moldávia'), ('Mônaco', 'Mônaco'), ('Montenegro', 'Montenegro'), ('Macedônia do Norte', 'Macedônia do Norte'), ('Noruega', 'Noruega'), ('Rússia', 'Rússia'), ('San Marino', 'San Marino'), ('Sérvia', 'Sérvia'), ('Suíça', 'Suíça'), ('Turquia', 'Turquia'), ('Ucrânia', 'Ucrânia'), ('Reino Unido', 'Reino Unido'), ('Vaticano', 'Vaticano')], default='Alemanha', max_length=255, verbose_name='País')),
                ('regiao', models.CharField(blank=True, default='', max_length=255, verbose_name='Região')),
                ('celular', models.CharField(blank=True, default='', max_length=500, verbose_name='Celular')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
                ('codigo', models.CharField(default='', max_length=255, unique=True, verbose_name='Código')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d', verbose_name='Foto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Colaborador Evento',
                'verbose_name_plural': 'Colaboradores Evento',
            },
        ),
    ]
