# Generated by Django 5.0.6 on 2024-09-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0029_colaboradoresevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradoresevento',
            name='email',
        ),
    ]
