# Generated by Django 5.0.6 on 2024-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0030_remove_colaboradoresevento_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
