# Generated by Django 5.0.6 on 2024-10-26 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0031_perfil_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('mensagem', models.TextField(default='', verbose_name='Mensagem')),
                ('recebida', models.BooleanField(default=False, verbose_name='Recebida?')),
                ('codigo', models.CharField(default='', max_length=255, verbose_name='Código')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_destinatario', to='perfil.perfil', verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_remetente', to='perfil.perfil', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem Chat',
                'verbose_name_plural': 'Mensagens Chat',
            },
        ),
    ]
