# Generated by Django 5.0.6 on 2024-10-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0033_alter_perfil_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d', verbose_name='Videos'),
        ),
    ]
