# Generated by Django 5.0.6 on 2024-08-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('tres_meses', 'Três Meses'), ('seis_meses', 'Seis Meses'), ('doze_meses', 'Doze Meses')], default='tres_meses', max_length=255, verbose_name='Nome')),
                ('preco', models.FloatField(default=0, verbose_name='Preco')),
                ('codigo', models.CharField(default='', max_length=2000, unique=True, verbose_name='Preco')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
