# Generated by Django 5.0.6 on 2024-08-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='codigo',
            field=models.CharField(default='', max_length=2000, unique=True, verbose_name='Código'),
        ),
    ]
