# Generated by Django 5.0.6 on 2024-08-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_plano_codigo'),
        ('perfil', '0020_alter_videochamada_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pedido', models.FloatField(default=0, verbose_name='Preço do pedido')),
                ('data_pedido', models.DateTimeField(auto_now=True, verbose_name='Data do pedido')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Última Atualização')),
                ('status_pedido', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20, verbose_name='Status Pedido')),
                ('id_user', models.CharField(default='', max_length=1000, verbose_name='Id User')),
                ('id_assinatura', models.CharField(default='', max_length=1000, verbose_name='Id Assinatura')),
                ('data_pagamento', models.CharField(default='', max_length=1000, verbose_name='Data Pagamento')),
                ('current_period_end', models.CharField(default='', max_length=1000, verbose_name='Current Period End')),
                ('plano_ativo', models.BooleanField(default=False, verbose_name='Plano Ativo')),
                ('recebeu_email_aprovado', models.BooleanField(default=False, verbose_name='Código Interno AP')),
                ('recebeu_email_reprovado', models.BooleanField(default=False, verbose_name='Código Interno REP')),
                ('recebeu_email_pendente', models.BooleanField(default=False, verbose_name='Código Interno PEN')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.perfil', verbose_name='Perfil')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
