# Generated by Django 5.0.6 on 2024-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('approved', 'approved'), ('cancel', 'cancel'), ('paused', 'paused'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20, verbose_name='Status Pedido'),
        ),
    ]
