# Generated by Django 5.0.6 on 2024-08-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_pedido_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_pagamento',
        ),
    ]
