# Generated by Django 5.0.6 on 2024-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_pedido_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='current_period_end',
            field=models.IntegerField(default=0, verbose_name='Current Period End'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Última Atualização'),
        ),
    ]
