# Generated by Django 5.0.6 on 2024-08-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_pedido_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_cancelar_assinatura',
            field=models.CharField(default='', max_length=255, verbose_name='Código C.A'),
        ),
    ]
