# Generated by Django 5.0.6 on 2024-08-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_qtd_participantes'),
        ('payment', '0008_remove_pedido_codigo_cancelar_assinatura'),
        ('perfil', '0024_videochamada_senha_reuniao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pedido', models.FloatField(default=0, verbose_name='Preço do pedido')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido')),
                ('status_pedido', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20, verbose_name='Status Pedido')),
                ('pagamento_feito', models.BooleanField(default=False, verbose_name='Pagamento Feito')),
                ('recebeu_email_aprovado', models.BooleanField(default=False, verbose_name='Código Interno AP')),
                ('recebeu_email_reprovado', models.BooleanField(default=False, verbose_name='Código Interno REP')),
                ('recebeu_email_pendente', models.BooleanField(default=False, verbose_name='Código Interno PEN')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.perfil', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
