# Generated by Django 5.0.6 on 2024-08-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_participantesevento_img_qrcode_and_more'),
        ('payment', '0009_pagamentoeventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentoeventos',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.evento', verbose_name='Evento'),
        ),
    ]
