# Generated by Django 5.0.6 on 2024-08-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_pagamentoeventos_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentoeventos',
            options={'verbose_name': 'Pagamento Evento', 'verbose_name_plural': 'Pagamento Eventos'},
        ),
    ]
