# Generated by Django 5.0.6 on 2024-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_pagamentoeventos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoeventos',
            name='payment_intent',
            field=models.CharField(default='', max_length=2000, verbose_name='Payment Intent'),
        ),
        migrations.AlterField(
            model_name='pagamentoeventos',
            name='status_pedido',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending'), ('refund', 'refund')], default='pending', max_length=20, verbose_name='Status Pedido'),
        ),
    ]
