# Generated by Django 5.0.6 on 2024-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_pagamentoeventos_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoeventos',
            name='id_reembolso',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Reembolso ID'),
        ),
    ]
