# Generated by Django 5.0.6 on 2024-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_pagamentoeventos_recebeu_email_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='evento_gratis',
            field=models.CharField(choices=[('nao', 'nao'), ('sim', 'sim')], default='nao', max_length=20, verbose_name='Tem direito a 1 evento grátis?'),
        ),
    ]
