# Generated by Django 5.0.6 on 2024-08-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_pedido_evento_gratis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_eventos_gratis',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Eventos Grátis'),
        ),
    ]
