# Generated by Django 5.0.6 on 2024-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_pedido_qtd_eventos_gratis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(choices=[('tres_meses', 'Três Meses'), ('seis_meses', 'Seis Meses'), ('doze_meses', 'Doze Meses'), ('tres_meses_promocional', 'Três Meses Promocional'), ('seis_meses_promocional', 'Seis Meses Promocional'), ('doze_meses_promocional', 'Doze Meses Promocional')], default='tres_meses', max_length=255, verbose_name='Nome'),
        ),
    ]
