# Generated by Django 5.0.6 on 2024-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_plano_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoeventos',
            name='qtd_criancas',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Crianças'),
        ),
    ]
