# Generated by Django 5.0.6 on 2024-09-12 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0030_remove_colaboradoresevento_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquearUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_bloqueado', to='perfil.perfil', verbose_name='Destinatário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to='perfil.perfil', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Comunication',
                'verbose_name_plural': 'Comunications',
            },
        ),
        migrations.CreateModel(
            name='Comunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('audio', 'audio'), ('video', 'video')], default='video', max_length=255, verbose_name='audio')),
                ('confirmacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunication_destinatario', to='perfil.perfil', verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunication_remetente', to='perfil.perfil', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Comunication',
                'verbose_name_plural': 'Comunications',
            },
        ),
    ]
