# Generated by Django 5.0.6 on 2024-09-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunication',
            name='link',
            field=models.URLField(default='', max_length=2000, verbose_name='Link'),
        ),
    ]
