# Generated by Django 5.0.6 on 2024-09-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0002_comunication_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunication',
            name='link',
        ),
        migrations.AddField(
            model_name='comunication',
            name='codigo',
            field=models.CharField(default='', max_length=2000, verbose_name='Código'),
        ),
    ]
