# Generated by Django 5.0.6 on 2024-09-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0003_remove_comunication_link_comunication_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunication',
            name='confirmacao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Expirado', 'Expirado'), ('Rejeitado', 'Rejeitado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=255, verbose_name='Confirmação'),
        ),
    ]
