# Generated by Django 5.0.6 on 2024-09-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0004_alter_comunication_confirmacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquearusuarios',
            options={'verbose_name': 'Bloquear Usuário', 'verbose_name_plural': 'Bloquear Usuários'},
        ),
    ]
