# Generated by Django 5.0.6 on 2024-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Preco'),
        ),
    ]
