# Generated by Django 5.0.6 on 2024-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_plano_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='banner_home/%Y/%m/%d', verbose_name='Banner 1')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='banner_home/%Y/%m/%d', verbose_name='Banner 2')),
                ('banner3', models.ImageField(blank=True, null=True, upload_to='banner_home/%Y/%m/%d', verbose_name='Banner 3')),
            ],
            options={
                'verbose_name': 'Carrossel',
                'verbose_name_plural': 'Carrossel',
            },
        ),
    ]
