# Generated by Django 5.0.6 on 2024-08-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carrossel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
