# Generated by Django 5.0.6 on 2024-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='link1',
            field=models.URLField(blank=True, max_length=3000, null=True, verbose_name='Link 1'),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='link2',
            field=models.URLField(blank=True, max_length=3000, null=True, verbose_name='Link 2'),
        ),
        migrations.AddField(
            model_name='carrossel',
            name='link3',
            field=models.URLField(blank=True, max_length=3000, null=True, verbose_name='Link 3'),
        ),
    ]
